add homework 2
JuliaOraz/nodejs-hw-rest-api pull request #1
Opened 2022-12-09 19:15 UTC by JuliaOraz

2022-12-10 08:38 UTC, BohdanGres requested changes
все супер, давай ще створимо мідлварку validateParams за аналогією з validateBody і схему для валідаці наших парамсі ну підключимо на роути в якиї воно летить

2022-12-10 08:39 UTC, BohdanGres commented on routes/api/contacts.js
> +const ctrl = require("../../controllers/contacts");
зроби більш зрозуміле ім`я

2022-12-10 12:06 UTC, JuliaOraz commented
> все супер, давай еще тщательно создадим междварку validateParams для аналогов с validateBody и схемой для проверки наших параметров, но обязательно на маршрутах в некоторых случаях во время полета

2022-12-10 12:17 UTC, JuliaOraz commented on routes/api/contacts.js
> +const ctrl = require("../../controllers/contacts");
Трохи не зрозуміла:) Потрібно зробити валідацію параметрів рядка запиту або параметрів тіла запиту?

2022-12-12 17:41 UTC, BohdanGres requested changes
все стало гарніше і охайніше, трошки переробити залишилось

2022-12-12 17:41 UTC, BohdanGres commented on middlewares/validateParams.js
> +    const { error } = schema.validate(req.params.contactId);
мідлварка має бути іневерсально, передаючи тут req.params.contactId цього вже не буде)
краще передавай req.params а саму схему зроби як об`єкт з полем contactId

2022-12-12 20:21 UTC, JuliaOraz commented
Дякую, виправила)

2022-12-13 07:54 UTC, BohdanGres approved these changes

2022-12-13 17:38 UTC, merged