Hw04 auth
JuliaOraz/nodejs-hw-rest-api pull request #3
Opened 2022-12-26 10:30 UTC by JuliaOraz

2022-12-26 20:08 UTC, BohdanGres requested changes

2022-12-26 20:08 UTC, BohdanGres commented on app.js
>  app.use("/api/contacts", contactsRouter);
спробуй тут навісити мідлварку, але перевір чи помилки правильно оброблюються

2022-12-26 20:08 UTC, BohdanGres commented on middlewares/authenticate.js
> +    if (!user || !user.token) {
ось тут треба ще перевірити user.token === token

2022-12-27 05:51 UTC, JuliaOraz commented
Виправила, помилки перевірила

2022-12-27 16:02 UTC, BohdanGres approved these changes

2022-12-27 16:02 UTC, BohdanGres commented on app.js
> +app.use("/api/users", authenticate, usersRouter);
на весь /api/users не треба тільки на /api/contacts

2022-12-28 11:18 UTC, merged